### ISSUE TITLE
If I run batch file of postigis2epanet it doesn't give any result

### ISSUE THREAD

**Issue by mirankunda** [JinIgarashi/postgis2epanet#1]
after double clicking the batch file of postgis2epanet it doesn't give any result @JinIgarashi 
![Batch file epanet](https://user-images.githubusercontent.com/60642018/93171544-94c6d580-f729-11ea-8eae-593790217b66.JPG)

**Comment by JinIgarashi** [comment]
@mirankunda 
I added docker for `postgis2epanet` module.
Could you try the following commands to produce INP files?

```
cd postgis2epanet
git reset --hard
git pull origin master
docker pull wasac/postgis2epanet:v2.0.0
```

check `docker-compose.yml` in text editor. Default setting is like this. I already put database settings. Please make sure settings are correct.
```yaml
version: '2'
services:
  python:
    image: wasac/postgis2epanet:v2.0.0
    # build: .
    environment:
     - db_user=postgres
     - db_password=wasacgis
     - db_host=host.docker.internal
     - db_port=5432
     - database=rwss_assets
     # If you want to specify districts to be exported, please put here like "51,52,53"
     - districts=
    volumes:
      - ./data:/tmp/src/data
```

When you want to export specific districts, you can edit yaml like below
```diff
-     - districts=
+     - districts=51,52
```

INP files will be created under `data` directory!
